java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  keyVaults:
    opal:
      secrets:
        - name: app-insights-connection-string
          alias: app-insights-connection-strings
  environment:
    OPAL_PRINT_DB_HOST: "{{ .Release.Name }}-postgresql"
    OPAL_PRINT_DB_NAME: "{{ .Values.postgresql.auth.database}}"
    OPAL_PRINT_DB_USERNAME: "{{ .Values.postgresql.auth.username}}"
    OPAL_PRINT_DB_PASSWORD: "{{ .Values.postgresql.auth.password}}"
    OPAL_PRINT_DB_OPTIONS: "?stringtype=unspecified"
    OPAL_PRINT_DB_PORT: 5432
    RUN_DB_MIGRATION_ON_STARTUP: true
  postgresql:
    enabled: true
